publish_cost_grid_pc: true
controller_frequency: 4.0
TrajectoryPlannerROS:
  
  max_vel_x: 0.5
  min_vel_x: 0.0
  max_vel_theta: 1.0
  
  controller_frequency: 4.0
  holonomic_robot: false
  meter_scoring: true
  
  gdist_scale: 0.8
  pdist_scale: 2.0
  occdist_scale: 0.01
  
  sim_time: 4.0
  
  dwa: true
