map_type: costmap

obstacle_range: 3.0
raytrace_range: 3.5

cost_scaling_factor: 2.4
inflation_radius: 1.5
robot_radius: 0.4

transform_tolerance: 0.1

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}
